name: Release Docker image for the app

on:
  pull_request:

jobs:
  build-and-push-image:
    runs-on: image-builder
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push
      uses: byzanteam/jet-actions/fe-build-image@chore/yangke/package-ali-github
      with:
        registries_key: ${{ secrets.GITHUB_TOKEN }}, ${{ secrets.ALIYUN_KEY }}
        registries_username: ${{ github.repository_owner }}, ${{ secrets.ALIYUN_ID }}
        registries: ghcr.io, registry.cn-hangzhou.aliyuncs.com
        registries_namespace: byzanteam, jet

