name: Release Docker image for the app

on:
  pull_request:

jobs:
  build-and-push-image:
    runs-on: image-builder
    #runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and push
      uses: byzanteam/jet-actions/fe-build-image@chore/yangke/package-ali-github
      with:
        #registries: |-
        #  ghcr.io,byzanteam,${{ github.repository_owner }},${{ secrets.PACKAGE_KEY }}
        #  registry.cn-hangzhou.aliyuncs.com,jet,${{ secrets.ALIYUN_ID }},${{ secrets.ALIYUN_KEY }}
        cache_type: local
