name: Release Docker image for the app

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push
      uses: byzanteam/jet-actions/fe-build-image@fix/yangke/image-name-miss
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        image_name: jet-autoflow-test
