name: Release Docker image for the app

on:
  pull_request:

jobs:
  build-and-push-image:
    runs-on: image-builder
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push
      uses: byzanteam/jet-actions/fe-build-image@chore/yangke/package-ali-github
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        aliyun_id: ${{ secrets.ALIYUN_ID }}
        aliyun_key: ${{ secrets.ALIYUN_KEY }}
        aliyun_namespace: jet

