name: Release Docker image for the app

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: jet
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push
      uses: byzanteam/jet-actions/fe-build-image@main
      with:
        registries: |-
          ${{ secrets.ALIYUN_JET_REGISTRY }}
          ghcr.io,byzanteam,${{ github.repository_owner }},${{ github.token }}
        cache_type: local
