name: Upgrade by docker compose

on:
  pull_request:
    branches:
      - main
jobs:
  compose-upgrade:
    runs-on: jet
    steps:
      - name: upgrade by compose
        uses: byzanteam/jet-actions/compose-upgrade@feat/yangke/docker-compose-upgrade
        with:
          host: 10.64.0.32
          user: root
          docker_compose_file_path: /opt/test-app/docker-compose.yml
          private_key: ${{ secrets.DEPLOYMENT_KEY }}
          service_name: jet-autoflow-example
          image_tag: registry.cn-hangzhou.aliyuncs.com/jet/jet-autoflow-example:sha-0e9577d
