name: "Upgrade by docker compose"

on:
  pull_request:

jobs:
  compose-upgrade:
    runs-on: image-builder
    steps:
      - name: Get APP Info
        uses: byzanteam/jet-actions/fe-get-app-info@main
        with:
          package_file: package.json
        id: get-app-info

      - name: upgrade by compose
        uses: byzanteam/jet-actions/compose-upgrade@feat/yangke/docker-compose-upgrade
        with:
          deploy_host: 10.64.0.32
          deploy_user: root
          deploy_to: /opt/test-app
          private_key: ${{ secrets.DEPLOYMENT_KEY }}
          image_name: ${{ steps.get-app-info.outputs.name }}
          image_version: ${{ steps.get-app-info.outputs.version }}
