name: Deploy to k8s

on:
  workflow_dispatch:

jobs:
  deploy-fe-app-k8s:
    runs-on: jet
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: deploy frontend application
        uses: byzanteam/jet-actions/deploy-frontend-application@chore/yangke/private-key
        with:
          image_tag: "0.0.11"
          private_key: ${{ vars.SSH_KEY_VAR }}
          namespace: test
