name: Deploy to k8s

on:
  workflow_dispatch:

jobs:
  deploy-fe-app-k8s:
    runs-on: jet
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: deploy frontend application
        uses: byzanteam/jet-actions/deploy-frontend-application@main
        with:
          image_tag: "0.0.11"
          private_key: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBOker9P00fGxKVeiG+10280Yz/I8Q7BS45W5J504+FtQAAAKAKiqZxCoqm
cQAAAAtzc2gtZWQyNTUxOQAAACBOker9P00fGxKVeiG+10280Yz/I8Q7BS45W5J504+FtQ
AAAEA1tiWfzSog+DXcwFBrxJiDgcV0bLEvBsZB9y8GcZQHOU6R6v0/TR8bEpV6Ib7XTbzR
jP8jxDsFLjlbknnTj4W1AAAAGmdpdGh1Yi1kZXBsb3llckBrOHMtbWFzdGVyAQID
-----END OPENSSH PRIVATE KEY-----"
          namespace: test
