name: Deploy this application to remote host

on:
  registry_package:
    types: [published]
  pull_request:
    types:
      - labeled


jobs:
  deploy:
    runs-on: jet
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: front deploy
        uses: byzanteam/jet-actions/deploy-frontend-application@feat/yangke/front-deploy
        with:
          values_file: "./deploy/example.values.yaml"
          image_tag: "latest"
          private_key: ${{ secrets.SSH_KEY }}
          release_name: example
